### ISSUE TITLE
Compile list of contributors and skillsets

### ISSUE THREAD

**Issue by Jiros** [covidgraph/documentation#31]
There are a growing number of people interested in contributing who have joined the main Matrix/Riot room. It would be helpful to extract a list of these along with their introductions/skillsets/offers of help and compile them into a meaningful list that can be searched or filtered or otherwise visualised to make it easier to identify people who may be able to help with any given task.

**Comment by Jiros** [comment]
Current plan is that @amorgner is considering a self-service registration process for covidgraph.org where people can register with their e-mail adress and create a user profile, approve publishing, maybe even manage a simple company profile, upload files etc.

**Comment by Jiros** [comment]
I just had a thought on this. Now that we have a CovidGraph LinkedIn Organisation page could we not just encourage contributors to add themselves as 'Volunteers' or 'Contributors' or something to that? Also good for their profiles no doubt. Then we can just signpost to the LinkedIn page from the main website and the wiki. Saves @amorgner setting up additional stuff on the website?

**Comment by mpreusse** [comment]
@Jiros great idea, I hope everyone who contributes is ok with that. 

We can still keep an informal list for internal use, but we don't have to publish it on the website.
