### ISSUE TITLE
Feedback Channels

### ISSUE THREAD

**Issue by Jiros** [covidgraph/documentation#33]
We need to establish one or more channels to capture end-user feedback. The first requirement for this is for the Visual Graph Explorer which is now ready for feedback.

Ideally these could be captured as GitHub issues but this would require end users to sign up for a github account.

Another option would be to have an email address for this e.g. feedback@covidgraph.org but no mail server or mail accounts exist yet and there is no resource to create and maintain these at present. 

Any other ideas or suggestions welcome!

**Comment by yGuy** [comment]
For the/my app itself, I could be piping feedback through our support channels at yWorks and I could be adding the requests to github, manually. But only for my app. And as soon there is another "official" channel, I would prefer that, of course.

**Comment by amorgner** [comment]
I've discussed e-mail feedback with Sebastian, and I have a strong take against using e-mail, primarily because of administration efforts, spam/abuse etc.. It's just difficult to handle.

My suggestion is to create a simple feedback form where people can select the app (pre-selected of course if we link directly from an app to the form). For now, I think it's sufficient if we secure the form with a simple captcha-like question. If there’s too much misuse, we'll put it behind a login (which is in the making anyways).

The feedback from the form will be saved in a database and sent to the owner(s) of the app. It could also be sent to the Riot channels via API (have to figure out how that works).

WDYT?

**Comment by yGuy** [comment]
TBH, I don't think we would be spammed that quickly. We have been using email and simple form based feedback channels for much much bigger projects and haven't had issues with this approach. But YMMV. But we can start big, too :-)

**Comment by Jiros** [comment]
@yGuy - Have you got a feedback channel in place for the Visual Graph Explorer yet? It's looking good and I had a few thoughts to share.

In terms of a feedback channel, if you wanted I can set up a fire-bot on the VGE repo and we could create an email address (e.g. vge@covidgraph.org) which can be pointed at the fire-bot to create isseus from email. That way we have a dedicated email address for your app that anyone can use to send feedback and it will automatically create a github issue. Let me know and I'll start setting it up.

**Comment by yGuy** [comment]
Yes, I like your proposal, so please go ahead and set things up accordingly! Thanks!

**Comment by Jiros** [comment]
OK, so I've added fire-bot as a collaborator and set up a fire.fundersclub email address

If @amorgner is able to create a new mailbox for vge@covidgraph.org and add a redirect to vge@fire.fundersclub.com then we can start to publicise the address for feedback and maybe add a feedback button on the website to use this address? 

Also, @yGuy - if you want notifications DM the best email address to use and I'll add it to the config.

I'll send a test once things are set up.

**Comment by Jiros** [comment]
Hi @amorgner 

I have just assigned this to you. I know you are busy at the moment but when you have a minute would you be able to create a new mailbox and redirect: 

1. create a new mailbox for vge@covidgraph.org and 
2. add a redirect to vge@fire.fundersclub.com then we can start to publicise the address for feedback and maybe add a feedback button on the website to use this address?

Thanks

**Comment by amorgner** [comment]
I just replaced the HubSpot inbox address by the above. Will now test it...

**Comment by Jiros** [comment]
Hi Axel - this is a separate address just for the visual graph explorer feedback which we are going to generate as issues directly as github issues using the fire-bot. The main contact address can remain unchanged for now.

**Comment by amorgner** [comment]
Ok, Cc: to the HubSpot inbox is restored. In the meantime there has been no incoming request, so nothing has been lost.

@Jiros Did you receive the test message in the fire-bot inbox?

**Comment by CleanEarthTrust** [comment]
Morning @amorgner 

I think I may have caused some confusion with the email addresses. Emails to the contact@covidgraph.org or notifications from the web form seem to be going to the visual graph repo as issues. I created this diagram to hopefully explain the set up a bit more clearly - would you be able to adjust the webform and mail server to match? 
[Inbound Channels](https://github.com/covidgraph/documentation/blob/master/diagrams/Inbound%20Channels.png)

I still get a mail delivery failure from vge@covidgraph.org which is the email address that we would like to redirect to the VGE repo via the fire-bot inbox.

(Logged into github as wrong user - Jamie)

**Comment by amorgner** [comment]
At them moment, there's only one contact form that is currently sending one e-mail to multiple To: or Cc: addresses.

I can change it so that it will send e-mails to specific adresses based on the type of inquiry.

And we also have to include a checkbox for people to agree for their feedback to be published in a GitHub repo.
