### ISSUE TITLE
Virtual machine for DEV instance

### ISSUE THREAD

**Issue by motey** [covidgraph/documentation#43]
To build a reliable pipeline and to have a transition-phase/adaptation-time for breaking changes we need a second machine.
I just went through all our options at the DZD with @jarasch, and we can not provide a VM faster than in two weeks, as our IT is in a minimal operation mode atm.
Anybody else who can help out here to conjure up a VM?
2-4 Cores
16-32 GB memory 
~300GB diskspace

**Comment by sarmbruster** [comment]
Neo4j happily sponsors this. Will do the basic setup and ping folks in infrastructure chat room with details.

**Comment by Jiros** [comment]
https://github.com/covidgraph/documentation/wiki/Dev-Test-server
