### ISSUE TITLE
Research Questions

### ISSUE THREAD

**Issue by Jiros** [covidgraph/documentation#77]
@jarasch @mpreusse @motey 

Although we have missed the deadline for submissions I wondered if these questions (from the original Cord-19 data source) are helpful from a #35 Researcher use case perspective: 

https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge/tasks

**Comment by motey** [comment]
Virtually all questions just raise `?` in my brain :D this is a task for the bionerds @jarasch @mpreusse :)
